### ISSUE TITLE
[BUG] Agent process doesn't start

### ISSUE THREAD

**Issue by secureme71** [utmstack/UTMStack#153] opened 2023-12-14 15:30 UTC
**Describe the bug**
Agent installer doesn't complete the installation

**To Reproduce**
 ./utmstack_agent_installer install
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
main.main()
        D:/Trabajo_programacion/go/src/github.com/KbaYero/UTMStack/agent/installer/main.go:51 +0xdbf

**Expected behavior**
Successfully installation

**Environment**
 - OS: Ubuntu 22.04
 - Version v10.1.0-202312131645

**Comment by Kbayero** [comment] 2023-12-15 09:56
@secureme71 
If you want to install the UTMStack agent for Linux, the installation command should look like this:
sudo apt update -y && sudo apt install wget -y && mkdir -p /opt/utmstack-linux-agent && wget -P /opt/utmstack-linux-agent https://cdn.utmstack.com/agent_updates/release/ installer/v10.1.2/utmstack_agent_installer && chmod -R 777 /opt/utmstack-linux-agent/utmstack_agent_installer && sudo /opt/utmstack-linux-agent/utmstack_agent_installer install my_ip_address my_connection_key yes
Instead, its installation command is ./utmstack_agent_installer install.

Please, to install UTMStack Agent, follow the steps in the **UTMStack Integrations section**. 
There you can find exactly the command you need to install an agent connected to your instance.

**Comment by secureme71** [comment] 2023-12-15 11:36
I have already tried but I have same error. 

Agent is not installed correctly. I have tried to install agent on UTMStack itself because I need to receive logs from firewalls.

**Comment by Kbayero** [comment] 2023-12-15 15:10
Send us the command you are using for the installation. Please make sure not to include sensitive information. Also send us the agent logs that can be found in /opt/utmstack-linux-agent/. In that path you will find several log files, send us their content to detect the error

**Comment by secureme71** [comment] 2023-12-15 16:32
I remove /etc/systemd/system/UTMStackModulesLogsCollector.service, /etc/systemd/system/multi-user.target.wants/UTMStackModulesLogsCollector.service, /etc/systemd/system/UTMStackAgent.service and /etc/systemd/system/multi-user.target.wants/UTMStackAgent.service files because uninstall command doesn't work well. 
I install again the agent and the installation works.

**Comment by secureme71** [comment] 2023-12-15 16:51
However, agent service doesn't work anymore after reboot. I waited for more than 30 minutes but agent doesn't start:

UTMStackAgent.service - UTMStack Agent Service
     Loaded: loaded (/etc/systemd/system/UTMStackAgent.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2023-12-15 17:49:15 CET; 26s ago
    Process: 16316 ExecStart=/opt/utmstack-linux-agent/utmstack_agent_service (code=exited, status=2)
   Main PID: 16316 (code=exited, status=2)
        CPU: 50ms

UTMStackRedline log says;

2023/12/15 17:48:54 UTMStackRedline ERROR: error checking exit status 2: error sending log : %!v(MISSING)
2023/12/15 17:48:59 UTMStackRedline INFO: UTMStackAgent service has been stopped
2023/12/15 17:49:00 UTMStackRedline ERROR: error checking exit status 2: error sending log : %!v(MISSING)
2023/12/15 17:49:05 UTMStackRedline INFO: UTMStackAgent service has been stopped
2023/12/15 17:49:05 UTMStackRedline ERROR: error checking exit status 2: error sending log : %!v(MISSING)
2023/12/15 17:49:10 UTMStackRedline INFO: UTMStackAgent service has been stopped
2023/12/15 17:49:10 UTMStackRedline ERROR: error checking exit status 2: error sending log : %!v(MISSING)
2023/12/15 17:49:15 UTMStackRedline INFO: UTMStackAgent service has been stopped
2023/12/15 17:49:15 UTMStackRedline ERROR: error checking exit status 2: error sending log : %!v(MISSING)
2023/12/15 17:49:20 UTMStackRedline INFO: UTMStackAgent service has been stopped
2023/12/15 17:49:20 UTMStackRedline ERROR: error checking exit status 2: error sending log : %!v(MISSING)
2023/12/15 17:49:25 UTMStackRedline INFO: UTMStackAgent service has been stopped
2023/12/15 17:49:25 UTMStackRedline ERROR: error checking exit status 2: error sending log : %!v(MISSING)
2023/12/15 17:49:30 UTMStackRedline INFO: UTMStackAgent service has been stopped
2023/12/15 17:49:30 UTMStackRedline ERROR: error checking exit status 2: error sending log : %!v(MISSING)
2023/12/15 17:49:35 UTMStackRedline INFO: UTMStackAgent service has been stopped
2023/12/15 17:49:35 UTMStackRedline ERROR: error checking exit status 2: error sending log : %!v(MISSING)

 UTMStackAgent.service                               loaded activating auto-restart UTMStack Agent Service
 UTMStackModulesLogsCollector.service      loaded active     running      UTMStackModulesLogsCollector
 UTMStackRedline.service                             loaded active     running      UTMStack Redline Service
 UTMStackUpdater.service                           loaded active     running      UTMStack Updater Service

**Comment by secureme71** [comment] 2023-12-21 23:43
Additional log:

2023/12/22 00:36:27 UTMStackAgent INFO: trying to connect to Server...
2023/12/22 00:36:27 UTMStackAgent ERROR: error sending High Priority Log to Log Auth Proxy: error sending logs to Log Auth Proxy: rpc error: code = Internal desc = header key "agent-key" contains value with non-printable ASCII characters

**Comment by Kbayero** [comment] 2023-12-22 13:45
@secureme71 Thank you for sending us the logs, with these we can do a deeper search to find the error. I will try to reproduce this same problem to solve it. As soon as we have the solution we will let you know

**Comment by secureme71** [comment] 2024-01-03 11:48
I have seen another message from log:

2024/01/03 12:37:41 UTMStackUpdater ERROR: error getting master version: invalid character '<' looking for beginning of value

**Comment by Kbayero** [comment] 2024-01-03 12:34
@secureme71 This error normally occurs when the agent tries to connect to the master and obtain the current version, but for some reason the master does not respond, it may be that at that moment it is offline or perhaps a container has been restarted due to an update or something similar, it is not a serious error message, it is just a warning, but the agent will continue trying to obtain the version

**Comment by secureme71** [comment] 2024-01-03 14:10
Ok. However the agent is always disconnected for the reason related to message "UTMStackAgent ERROR: error sending High Priority Log to Log Auth Proxy: error sending logs to Log Auth Proxy: rpc error: code = Internal desc = header key "agent-key" contains value with non-printable ASCII characters".

**Comment by Kbayero** [comment] 2024-01-03 17:17
@secureme71 This Issue is especially dedicated to that problem you mention, as you can see it is in review status. Initially the agent was not intended to be installed on the same machine where the master is located. After you reported that problem, we have been working on that problem to make it work, currently we have fixed said problem and we are testing that fix to update it in the next version. That's why I haven't closed the Issue so I can let you know when it's ready.

**Comment by Kbayero** [comment] 2024-01-05 21:53
@secureme71 I want to inform you that the UTMStack agent installation issue you reported has been resolved. 
As a result, we will be closing this Issue. If you find any problem or have additional questions in the future, please don't hesitate to reopen the issue.

To complete the resolution process, please execute the following command for uninstall the current agent:
```
sudo /opt/utmstack-linux-agent/utmstack_agent_installer uninstall || true; sudo systemctl stop UTMStackAgent 2>/dev/null || true; sudo systemctl disable UTMStackAgent 2>/dev/null || true; sudo rm /etc/systemd/system/UTMStackAgent.service 2>/dev/null || true; sudo systemctl stop UTMStackRedline 2>/dev/null || true; sudo systemctl disable UTMStackRedline 2>/dev/null || true; sudo rm /etc/systemd/system/UTMStackRedline.service 2>/dev/null || true; sudo systemctl stop UTMStackUpdater 2>/dev/null || true; sudo systemctl disable UTMStackUpdater 2>/dev/null || true; sudo rm /etc/systemd/system/UTMStackUpdater.service 2>/dev/null || true; sudo systemctl stop UTMStackModulesLogsCollector 2>/dev/null || true; sudo systemctl disable UTMStackModulesLogsCollector 2>/dev/null || true; sudo rm /etc/systemd/system/UTMStackModulesLogsCollector.service 2>/dev/null || true; sudo systemctl daemon-reload 2>/dev/null || true; echo "Removing UTMStack Agent dependencies..." && sleep 10 && sudo rm -rf "/opt/utmstack-linux-agent" && echo "UTMStack Agent dependencies removed successfully."
```
After uninstalling, reinstall the UTMStack agent using the Windows Agent Integration Guide.

To ensure a successful installation, navigate to the /opt/utmstack-linux-agent/ path and check the content of the versions.json file, this should show something like this:
```
{
    "master_version": "10.1.0",
    "agent_version": "10.1.2",
    "updater_version": "10.1.3",
    "redline_version": "10.1.2"
}
```

**Closed** 2024-01-05 22:57 UTC
Labels: bug
